services:
  postgres:
    image: postgres:16-alpine
    container_name: csswars-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: